const fs = require('fs');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.generated.ts');
const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY || '';

const content = `// Auto-generated by scripts/sync-env.js — do not edit manually
export const envSecrets = {
  googleMapsApiKey: ${JSON.stringify(googleMapsApiKey)},
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('[sync-env] Wrote environment.generated.ts');
